resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - metrics_auth_role.yaml
  - metrics_auth_role_binding.yaml
  - metrics_reader_role.yaml
  - neo4jauthrule_editor_role.yaml
  - neo4jauthrule_viewer_role.yaml
  - neo4jbackup_editor_role.yaml
  - neo4jbackup_viewer_role.yaml
  - neo4jdatabase_editor_role.yaml
  - neo4jdatabase_viewer_role.yaml
  - neo4jenterprisecluster_editor_role.yaml
  - neo4jenterprisecluster_viewer_role.yaml
  - neo4jenterprisestandalone_editor_role.yaml
  - neo4jenterprisestandalone_viewer_role.yaml
  - neo4jplugin_editor_role.yaml
  - neo4jplugin_viewer_role.yaml
  - neo4jrestore_editor_role.yaml
  - neo4jrestore_viewer_role.yaml
  - neo4jrole_editor_role.yaml
  - neo4jrole_viewer_role.yaml
  - neo4jrolebinding_editor_role.yaml
  - neo4jrolebinding_viewer_role.yaml
  - neo4jshardeddatabase_editor_role.yaml
  - neo4jshardeddatabase_viewer_role.yaml
  - neo4juser_editor_role.yaml
  - neo4juser_viewer_role.yaml
