apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neo4j-operator-system

resources:
  - ../../default

images:
  - name: controller
    newName: ghcr.io/neo4j-partners/neo4j-kubernetes-operator
    newTag: latest

patches:
  - path: ha-patch.yaml
    target:
      kind: Deployment
      name: controller-manager
