apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - neo4j_v1beta1_auracustomermanagedkey.yaml
  - neo4j_v1beta1_auradatabase.yaml
  - neo4j_v1beta1_auradatabasebackup.yaml
  - neo4j_v1beta1_auradatabaserestore.yaml
  - neo4j_v1beta1_aurainstance.yaml
  - neo4j_v1beta1_aurainvite.yaml
  - neo4j_v1beta1_auraipfilter.yaml
  - neo4j_v1beta1_auraorganizationmember.yaml
  - neo4j_v1beta1_auraprojectmember.yaml
  - neo4j_v1beta1_auraproviderconfig.yaml
  - neo4j_v1beta1_aurarestore.yaml
  - neo4j_v1beta1_aurasnapshot.yaml
  - neo4j_v1beta1_neo4jauthrule.yaml
  - neo4j_v1beta1_neo4jbackup.yaml
  - neo4j_v1beta1_neo4jdatabase.yaml
  - neo4j_v1beta1_neo4jdatabasealias.yaml
  - neo4j_v1beta1_neo4jenterprisecluster.yaml
  - neo4j_v1beta1_neo4jenterprisestandalone.yaml
  - neo4j_v1beta1_neo4jplugin_cluster.yaml
  - neo4j_v1beta1_neo4jplugin_standalone.yaml
  - neo4j_v1beta1_neo4jreplicadatabase.yaml
  - neo4j_v1beta1_neo4jreplicapromotion.yaml
  - neo4j_v1beta1_neo4jrestore.yaml
  - neo4j_v1beta1_neo4jrole.yaml
  - neo4j_v1beta1_neo4jrolebinding.yaml
  - neo4j_v1beta1_neo4jshardeddatabase.yaml
  - neo4j_v1beta1_neo4juser.yaml
